app:
  name: sourcewair

spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml
  main:
    allow-bean-definition-overriding: true

server:
  port: 8010

APP_HOME: ${APP_HOME}

#DATA config
DATA_HOME: ${user.home}/tiklab/sourcewair

#database config
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5431/sourcewair_ce?stringtype=unspecified
  username: postgres
  password: darth2020

postgresql:
  embbed:
    enable: true
  database: tiklab_sourcewair
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql


#dcs config
dcs:
  server:
    enabled: true
    mode: server
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200


# (local:本地登录  soular:统一登录)
auth:
  type: local
  soular:
    address: ""



external:
  url: http://eas-ce.demo.tiklab.net



