app:
  name: tiklab-sourcefare
  version: ee

APP_HOME: ${APP_HOME}
application: sourcefare

server:
  port: 8090


jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5435/tiklab_sourcefare?stringtype=unspecified
  username: postgres
  password: darth2020


#plugin config
DATA_HOME: /opt/tiklab/sourcefare


postgresql:
  embbed:
    enable: true
  database: tiklab_sourcefare
  db:
    port: 5435
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

# (local:本地登录  soular:统一登录)
auth:
  type: soular
  soular:
    address: http://e.tiklab.net
  expire: 86400 # 过期时间，单位秒，默认1天

#dcs config
dcs:
  server:
    enabled: true
    mode: server
    port: 5005
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5005
    group: g1
    database: dcs1
    expire: 7200

external:
  url: http://e.eas.tiklab.net
