#application config
app:
  name: tiklab-sourcewair
  path: ${APP_HOME}
  version: ce

#web config
server:
  port: 8090

#dal config

#dal config for mysql jdbc
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5490/tiklab_sourcefare?stringtype=unspecified
  username: postgres
  password: darth2020


postgresql:
  embbed:
    enable: true
  database: tiklab_sourcefare
  db:
    port: 5490
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

#soular config
soular:
  embbed:
    enable: false
  address: http://soular-ce.demo.tiklab.net

DATA_HOME: /opt/thoughtware/sourcefare

base:
  url: http://soular-ce.demo.tiklab.net

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4100
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4100
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: true
    mode: server
    port: 5100
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5100
    group: g1
    database: dcs1
    expire: 7200

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6100
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6100
    bucket: ${app.name}


#plugin config
plugin.path: ${APP_HOME}/plugin


homes:
  address: http://homes.tiklab.net


#licences config
licences:
  path: ${DATA_HOME}/licences

#file
file:
  path: http://file.thoughtware.net

repository:
  address: ${DATA_HOME}/repository



backups:
  time: 0 0 2 * * ?
  dir: /data/backup
  xpack:
    dir: ${DATA_HOME}/repository


postin:
  scan:
    package: io.tiklab.hadess