app:
  name: tiklab-sourcefare


server:
  port: 8010

APP_HOME: ${APP_HOME}

DATA_HOME: ${user.home}/tiklab/${app.name}

#database config
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_sourcefare?stringtype=unspecified
   #url: jdbc:postgresql://172.13.1.23:5435/tiklab_sourcefare?stringtype=unspecified
  username: postgres
  password: darth2020

# Enable the embedded database
postgresql:
  embbed:
    enable: false
  type: local
  database: tiklab_sourcefare

#dcs config
dcs:
  server:
    enabled: true
    port: 5001
    datapath: ${DATA_HOME}/data
  client:
    url: 127.0.0.1:5001
    group: g1
    database: dcs1
    expire: 7200


# (local:本地登录  soular:统一登录)
auth:
  type: local
  soular:
    address: http://192.168.10.15:8080
  expire: 86400 # 过期时间，单位秒，默认1天

external:
  url: http://192.168.10.9:8090




