app:
  name: tiklab-sourcewair

spring:
  main:
    allow-bean-definition-overriding: true
  freemarker:
    checkTemplateLocation: false

server:
  port: 8010

APP_HOME: ${APP_HOME}

DATA_HOME: ${user.home}/tiklab/${app.name}

#database config
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/sourcewair_ce?stringtype=unspecified
  username: postgres
  password: darth2020

# Enable the embedded database
postgresql:
  embbed:
    enable: false
  type: local
  database: tiklab-sourcewair

#dcs config
dcs:
  server:
    enabled: true
    port: 5001
    datapath: ${DATA_HOME}/data
  client:
    url: 127.0.0.1:5001
    group: g1
    database: dcs1
    expire: 7200

soular:
  embbed:
    enable: true

message:
  sms:
    enabled: true

base:
  url: http://192.168.10.9:8090

repository:
  address: ${DATA_HOME}/repository


ws:
  name: local
  server:
    enabled: true
  enterprise: default
  url : localhost:8091

#license
licences:
  path: ${DATA_HOME}/licences


backups:
  time: 0 0 2 * * ?
  dir: ${DATA_HOME}/backups
  xcode:
    dir: ${DATA_HOME}/repository


spotbugs:
  address: /embbed/spotbugs-4.8.1/bin

postin:
  scan:
    package: io.tiklab.sourcewair
