<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>io.tiklab</groupId>
		<artifactId>tiklab-sourcefare</artifactId>
		<version>1.0.2</version>
	</parent>


	<artifactId>tiklab-sourcefare-starter</artifactId>
	<name>${project.artifactId}</name>

	<dependencies>
		<dependency>
			<groupId>io.tiklab</groupId>
			<artifactId>tiklab-postgresql-starter</artifactId>
			<version>${tiklab-postgresql.version}</version>
		</dependency>
		<dependency>
			<groupId>io.tiklab</groupId>
			<artifactId>tiklab-toolkit-spring-boot-starter</artifactId>
			<version>${tiklab-toolkit.version}</version>
		</dependency>
		<dependency>
			<groupId>io.tiklab</groupId>
			<artifactId>tiklab-eam-spring-boot-starter</artifactId>
			<version>${tiklab-eam.version}</version>
		</dependency>
		<dependency>
			<groupId>io.tiklab</groupId>
			<artifactId>tiklab-user-spring-boot-starter</artifactId>
			<version>${tiklab-user.version}</version>
		</dependency>
		<dependency>
			<groupId>io.tiklab</groupId>
			<artifactId>tiklab-message-spring-boot-starter</artifactId>
			<version>${tiklab-message.version}</version>
		</dependency>

		<dependency>
			<groupId>io.tiklab</groupId>
			<artifactId>tiklab-sourcefare-server</artifactId>
			<version>${project.version}</version>
		</dependency>


		<dependency>
			<groupId>io.tiklab</groupId>
			<artifactId>tiklab-licence-spring-boot-starter</artifactId>
			<version>${tiklab-licence.version}</version>
		</dependency>
		<dependency>
			<groupId>io.tiklab</groupId>
			<artifactId>tiklab-gateway-spring-boot-starter</artifactId>
			<version>${tiklab-gateway.version}</version>
		</dependency>
		<dependency>
			<groupId>io.tiklab</groupId>
			<artifactId>tiklab-rpc-spring-boot-starter</artifactId>
			<version>${tiklab-rpc.version}</version>
		</dependency>
		<dependency>
			<groupId>io.tiklab</groupId>
			<artifactId>tiklab-dss-spring-boot-starter</artifactId>
			<version>${tiklab-dss.version}</version>
		</dependency>
		<dependency>
			<groupId>io.tiklab</groupId>
			<artifactId>tiklab-dfs-spring-boot-starter</artifactId>
			<version>${tiklab-dfs.version}</version>
		</dependency>
		<dependency>
			<groupId>io.tiklab</groupId>
			<artifactId>tiklab-dcs-spring-boot-starter</artifactId>
			<version>${tiklab-dcs.version}</version>
		</dependency>

		<dependency>
			<groupId>io.tiklab</groupId>
			<artifactId>tiklab-security-spring-boot-starter</artifactId>
			<version>${tiklab-security.version}</version>
		</dependency>


		<!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-api -->
<!--		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>2.0.5</version>
		</dependency>-->

		<dependency>
			<groupId>io.tiklab</groupId>
			<artifactId>tiklab-dsm-spring-boot-starter</artifactId>
			<version>${tiklab-dsm.version}</version>
		</dependency>
		<dependency>
			<groupId>io.tiklab</groupId>
			<artifactId>tiklab-openapi-spring-boot-starter</artifactId>
			<version>${tiklab-openapi-version}</version>
		</dependency>
		<dependency>
			<groupId>io.tiklab</groupId>
			<artifactId>tiklab-postin-doclet</artifactId>
			<version>${tiklab-postin-doclet-version}</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.25</version>
		</dependency>

		<dependency>
			<groupId>io.tiklab</groupId>
			<artifactId>tiklab-install-server</artifactId>
			<version>1.0.2</version>
		</dependency>
		<dependency>
			<groupId>io.tiklab</groupId>
			<artifactId>tiklab-install-client</artifactId>
			<version>1.0.2</version>
		</dependency>
		<dependency>
			<groupId>io.tiklab</groupId>
			<artifactId>tiklab-rpc-spring-boot-starter</artifactId>
			<version>${tiklab-rpc.version}</version>
		</dependency>
	</dependencies>

	<profiles>

		<!--linux-->
		<profile>
			<id>system-linux</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<dependencies>
				<dependency>
					<groupId>io.tiklab</groupId>
					<artifactId>tiklab-jdk-linux</artifactId>
					<version>${tiklab-jdk.version}</version>
					<type>zip</type>
					<scope>provided</scope>
				</dependency>
				<dependency>
					<groupId>io.tiklab</groupId>
					<artifactId>tiklab-postgresql-linux</artifactId>
					<version>${tiklab-postgresql.version}</version>
					<type>zip</type>
					<scope>provided</scope>
				</dependency>
				<dependency>
					<groupId>io.tiklab</groupId>
					<artifactId>tiklab-spotbugs</artifactId>
					<version>${tiklab-spotbugs.version}</version>
					<type>zip</type>
					<scope>provided</scope>
				</dependency>
			</dependencies>
			<properties>
				<assembly>linux</assembly>
				<systemType>linux</systemType>
			</properties>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-dependency-plugin</artifactId>
						<version>2.8</version>
						<executions>
							<execution>
								<id>unpack</id>
								<phase>compile</phase>
								<goals>
									<goal>unpack</goal>
								</goals>
								<configuration>
									<artifactItems>
										<artifactItem>
											<groupId>io.tiklab</groupId>
											<artifactId>tiklab-postgresql-linux</artifactId>
											<version>${tiklab-postgresql.version}</version>
											<type>zip</type>
											<outputDirectory>embbed</outputDirectory>
										</artifactItem>
										<artifactItem>
											<groupId>io.tiklab</groupId>
											<artifactId>tiklab-jdk-linux</artifactId>
											<version>${tiklab-jdk.version}</version>
											<type>zip</type>
											<outputDirectory>embbed</outputDirectory>
										</artifactItem>
										<artifactItem>
											<groupId>io.tiklab</groupId>
											<artifactId>tiklab-spotbugs</artifactId>
											<version>${tiklab-spotbugs.version}</version>
											<type>zip</type>
											<outputDirectory>embbed</outputDirectory>
										</artifactItem>
									</artifactItems>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>

		<!--windows-->
		<profile>
			<id>system-windows</id>
			<dependencies>
				<dependency>
					<groupId>io.tiklab</groupId>
					<artifactId>tiklab-jdk-windows</artifactId>
					<version>${tiklab-jdk.version}</version>
					<type>zip</type>
					<scope>provided</scope>
				</dependency>
				<dependency>
					<groupId>io.tiklab</groupId>
					<artifactId>tiklab-postgresql-windows</artifactId>
					<version>${tiklab-postgresql.version}</version>
					<type>zip</type>
					<scope>provided</scope>
				</dependency>
				<dependency>
					<groupId>io.tiklab</groupId>
					<artifactId>tiklab-spotbugs</artifactId>
					<version>${tiklab-spotbugs.version}</version>
					<type>zip</type>
					<scope>provided</scope>
				</dependency>
			</dependencies>
			<properties>
				<assembly>windows</assembly>
				<systemType>windows</systemType>
			</properties>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-dependency-plugin</artifactId>
						<version>2.8</version>
						<executions>
							<execution>
								<id>unpack</id>
								<phase>compile</phase>
								<goals>
									<goal>unpack</goal>
								</goals>
								<configuration>
									<artifactItems>
										<artifactItem>
											<groupId>io.tiklab</groupId>
											<artifactId>tiklab-jdk-windows</artifactId>
											<version>${tiklab-jdk.version}</version>
											<type>zip</type>
											<outputDirectory>embbed</outputDirectory>
										</artifactItem>
										<artifactItem>
											<groupId>io.tiklab</groupId>
											<artifactId>tiklab-postgresql-windows</artifactId>
											<version>${tiklab-postgresql.version}</version>
											<type>zip</type>
											<outputDirectory>embbed</outputDirectory>
										</artifactItem>
										<artifactItem>
											<groupId>io.tiklab</groupId>
											<artifactId>tiklab-spotbugs</artifactId>
											<version>${tiklab-spotbugs.version}</version>
											<type>zip</type>
											<outputDirectory>embbed</outputDirectory>
										</artifactItem>
									</artifactItems>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>

		<!--mac-->
		<profile>
			<id>system-mac</id>
			<dependencies>
				<dependency>
					<groupId>io.tiklab</groupId>
					<artifactId>tiklab-jdk-mac</artifactId>
					<version>${tiklab-jdk.version}</version>
					<type>zip</type>
					<scope>provided</scope>
				</dependency>
				<dependency>
					<groupId>io.tiklab</groupId>
					<artifactId>tiklab-postgresql-mac</artifactId>
					<version>${tiklab-postgresql.version}</version>
					<type>zip</type>
					<scope>provided</scope>
				</dependency>
				<dependency>
					<groupId>io.tiklab</groupId>
					<artifactId>tiklab-spotbugs</artifactId>
					<version>${tiklab-spotbugs.version}</version>
					<type>zip</type>
					<scope>provided</scope>
				</dependency>
			</dependencies>
			<properties>
				<assembly>mac</assembly>
				<systemType>mac</systemType>
			</properties>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-dependency-plugin</artifactId>
						<version>2.8</version>
						<executions>
							<execution>
								<id>unpack</id>
								<phase>compile</phase>
								<goals>
									<goal>unpack</goal>
								</goals>
								<configuration>
									<artifactItems>
										<artifactItem>
											<groupId>io.tiklab</groupId>
											<artifactId>tiklab-postgresql-mac</artifactId>
											<version>${tiklab-postgresql.version}</version>
											<type>zip</type>
											<outputDirectory>embbed</outputDirectory>
										</artifactItem>
										<artifactItem>
											<groupId>io.tiklab</groupId>
											<artifactId>tiklab-jdk-mac</artifactId>
											<version>${tiklab-jdk.version}</version>
											<type>zip</type>
											<outputDirectory>embbed</outputDirectory>
										</artifactItem>
										<artifactItem>
											<groupId>io.tiklab</groupId>
											<artifactId>tiklab-spotbugs</artifactId>
											<version>${tiklab-spotbugs.version}</version>
											<type>zip</type>
											<outputDirectory>embbed</outputDirectory>
										</artifactItem>
									</artifactItems>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>

		<!--dev-->
		<profile>
			<id>env-dev</id>
			<properties>
				<yaml-type>/config/dev</yaml-type>
			</properties>
		</profile>

		<!--dasasdas-->
		<profile>
			<id>env-test</id>
			<properties>
				<yaml-type>/config/test</yaml-type>
			</properties>
		</profile>

		<profile>
			<id>env-pack-linux</id>
			<properties>
				<yaml-type>/config/pac/linux</yaml-type>
			</properties>
		</profile>
		<profile>
			<id>env-pack-mac</id>
			<properties>
				<yaml-type>/config/pac/mac</yaml-type>
			</properties>
		</profile>
		<profile>
			<id>env-pack-windows</id>
			<properties>
				<yaml-type>/config/pac/windows</yaml-type>
			</properties>
		</profile>

		<!--demo-->
		<profile>
			<id>env-demo-ce</id>
			<properties>
				<yaml-type>/config/demo/ce</yaml-type>
			</properties>
		</profile>
		<profile>
			<id>env-demo-ee</id>
			<properties>
				<yaml-type>/config/demo/ee</yaml-type>
			</properties>
		</profile>
		<profile>
			<id>env-prd</id>
			<properties>
				<yaml-type>/config/prd</yaml-type>
			</properties>
		</profile>

		<!--release-->
		<profile>
			<id>env-release</id>
			<properties>
				<yaml-type>/</yaml-type>
			</properties>
		</profile>
	</profiles>



	<build>
		<plugins>
			<!--jar去掉配置文件-->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>*.yaml</exclude>
						<exclude>*.properties</exclude>
						<exclude>*.xml</exclude>
						<exclude>**/config/dev/**</exclude>
						<exclude>**/config/test/**</exclude>
					</excludes>
				</configuration>
			</plugin>

			<!--跳过发包-->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>

			<!--maven打包插件-->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<executions>
					<execution>
						<id>make-assembly</id>
						<configuration>
							<descriptors>
								<descriptor>assembly/distribution.xml</descriptor>
							</descriptors>
						<!--	<finalName>tiklab-sourcewair-${version}-${timestamp}</finalName>-->
							<finalName>tiklab-sourcewair-1.0.0</finalName>
							<appendAssemblyId>false</appendAssemblyId>
						</configuration>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>


			<!--清理之前的目录-->
			<plugin>
				<artifactId>maven-clean-plugin</artifactId>
				<version>2.5</version>
				<executions>
					<execution>
						<id>auto-clean</id>
						<phase>initialize</phase>
						<goals>
							<goal>clean</goal>
						</goals>
						<configuration>
							<skip>false</skip>
							<filesets>
								<fileset>
									<directory>${basedir}/embbed</directory>
								</fileset>
							</filesets>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<!--copy插件-->
			<!--<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.8</version>
				<executions>
					<execution>
						<phase>prepare-package</phase>
						<goals>
							<goal>copy</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<artifactItems>
						<artifactItem>
							<groupId>io.tiklab</groupId>
							<artifactId>tiklab-user-plugin-all</artifactId>
							<version>${project.version}</version>
						</artifactItem>
					</artifactItems>
					<includeTypes>jar</includeTypes>
					<outputDirectory>${project.basedir}/plugin</outputDirectory>
				</configuration>
			</plugin>-->

			<!--postin-doclet-->
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>3.0.0</version>
				<executions>
					<execution>
						<phase>test</phase>
						<goals>
							<goal>java</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<mainClass>io.tiklab.postin.doclet.starter.DocletApplication</mainClass>
					<arguments>
						<!-- modules 传入api，server两个文件-->
						<argument>/Users/limingliang/xcode-xpack/tiklab-sourcewair/tiklab-sourcewair-api;/Users/limingliang/xcode-xpack/tiklab-sourcewair/tiklab-sourcewair-server</argument>
						<!-- workspaceId 空间Id，放到哪个空间-->
						<argument>61887b155f39</argument>
						<!-- server  postin服务-->
						<argument>http://192.168.10.21:8090</argument>
					</arguments>
				</configuration>
			</plugin>
		</plugins>
	</build>



</project>
